"""empty message

Revision ID: 33c5af526628
Revises: 
Create Date: 2022-11-23 21:41:50.536869

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '33c5af526628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('float_messages',
                    sa.Column('time', sa.DateTime(), nullable=False),
                    sa.Column('data', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('time')
                    )
    op.create_table('int_messages',
                    sa.Column('time', sa.DateTime(), nullable=False),
                    sa.Column('data', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('time')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('int_messages')
    op.drop_table('float_messages')
    # ### end Alembic commands ###
